site_name: 4doc-style Gradle docs
site_url: https://gradle-dr4n3.ondigitalocean.app/
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Reference:
    - glossary.md
    - javadoc.md
  - How-to-guides:
    - how-to-guides/working-with-files.md
    - how-to-guides/invoking-shell-commands.md
  - Explanations:
    - explanations/build-phases.md
    - explanations/task-graph.md
    - explanations/multi-project-builds.md
    - explanations/up-to-date-checking.md
    - explanations/task-output-caching.md
    - explanations/configuration-caching.md
  - Tutorials:
    - tutorials/extract-project-build-to-an-included-build-plugin.md
    - tutorials/migrate-buildSrc-to-included-build-plugins.md
  - Conceptual Overviews:
      - conceptual-overviews/build.md
      - conceptual-overviews/project.md
      - conceptual-overviews/plugin.md
  - FAQs: faqs.md
  - Troubleshooting: troubleshooting.md
  - Best Practices: best-practices.md
  - Cheat Sheet: cheat-sheet.md
theme: 
  name: material
  features:
    - navigation.expand
markdown_extensions:
  toc:
    permalink: true
