site_name: 4doc-style Gradle Build Tool docs
site_url: https://docs.fly.dev
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Reference:
    - reference/glossary.md
    - reference/javadoc.md
  - Overview:
    - overview/what-is-gradle.md
    - overview/usage-tradeoffs.md
    - overview/values-and-themes.md
  - Basics:
    - baseline/working-with-files.md
    - baseline/invoking-shell-commands.md
  - Features:
    - explanations/multi-project-builds.md
    - explanations/up-to-date-checking.md
    - explanations/task-output-caching.md
    - explanations/configuration-caching.md
  - Tutorials:
    - tutorials/extract-project-build-to-an-included-build-plugin.md
    - tutorials/migrate-buildSrc-to-included-build-plugins.md
    - tutorials/monorepo.md
  - Concepts:
    - concepts/build.md
    - concepts/project.md
    - concepts/plugin.md
  - FAQs: faqs.md
  - Troubleshooting: troubleshooting.md
  - Best Practices: best-practices.md
  - Cheat Sheet: cheat-sheet.md
theme:
  name: material
  features:
    - navigation.expand
markdown_extensions:
  toc:
    permalink: true
